apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  labels: 
    app: mongo
    tier: mongoapp
  name: mongo-replicaset
  namespace: payapp-namespace
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      tier: mongoapp
  template: 
    metadata: 
      labels: 
        tier: mongoapp
    spec: 
      containers: 
        - 
          image: mongo
          name: mongo-app
          ports: 
            - 
              containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
   name: mongo-service
   namespace: payapp-namespace
spec:
  selector:
    app: mongo-app
  ports:
   - protocol: TCP
     port: 27017
     targetPort: 27017